# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e650b15a9582fd30d82387affebe72688a2e63f7ab78130d73fe4ea8f009463de9a175b4ce41c3fb95381155b375961721938689d4c1569a44ba2b18cc11f9

test:
  secret_key_base: 736c194048b6ad4e472f0b2689b638adb0b0a50aff36cffa5ddc82312516c5f1c8a91721c7df38a068a0733369e3197d920be2131d9bfbaa2e73c0c09a0bed41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
